name: CI – shared packages

on:
  push:
    paths:
      - 'packages/pkg-shared/**'

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/pkg-shared
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Build package
        run: npm run build
